### PR TITLE
Use pip install --report over pip-compile

### PR DESCRIPTION
**Pull request by mitsuhiko**
This hack uses a pip that is temporarily added to the virtualenv as an alternative over `pip-compile`. It does not fully address #82 but it covers some common cases.

Before merging this, some tests should be added to establish some baseline of installable packages.

Things to do before merge:

* [ ] add tests for some common scenarios
* [ ] restore `--upgrade` support for single packages

### CODE REVIEW

**Comment by mitsuhiko** [comment]
One significant downside of this approach over `pip-tools` is that the latter can resolve bad constraints. So for instance if you pin a dependency to too low version, it will manage to break that pin. `pip` on the other hand just bails hard

```
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
…

The conflict is caused by:
    flask 2.3.2 depends on Werkzeug>=2.3.3
    The user requested (constraint) werkzeug==2.2.0
```

**Comment by mitsuhiko** [comment]
I don't think that this is the path to go given the restrictions of this approach.

**Comment by davegaeddert** [comment]
@mitsuhiko just curious, what's the gist of the issues? Only the resolution thing you mentioned above, or more than that?

**Comment by mitsuhiko** [comment]
@davegaeddert one is the issue that it can’t resolve outdated pins, another is that it’s unclear how to upgrade single packages

**Pull request closed without merging**
