### PR TITLE
bump uv to 0.1.3

### PR DESCRIPTION
**Pull request by sbarrios93**

### CODE REVIEW

**Comment by cnpryer** [comment]
You'll want to bump `SELF_VERSION` as well.

**Comment by cnpryer** [comment]
Actually, depending on how Armin is intends on using `SELF_VERSION`, this might be able to sneak into v12.

**Comment by sbarrios93** [comment]
Good catch @cnpryer! I'll wait for his comment and update if necessary

**Comment by mitsuhiko** [comment]
Done now in another PR too. I did not bump `SELF_VERSION` since I just did for 0.1.2.

**Pull request closed without merging**
