### PR TITLE
Allow using system python for self environment

### PR DESCRIPTION
**Pull request by charbeljc**
Hello,

I really *love* rye's user XP. This is *so* refreshing...

This patch:

 * make `matches_version()` public.
 * add `ensure_toolchain(&PythonVersionRequest)`.
 * allow using preregistered toolchains for rye's self environments.

This is very useful in places where downloading a python build from random other places is a no no, because fighting corporate proxies & firewalls to get job done is no fun (hello zscaler).

Oh, also, as a bonus, this adds an option `--dbg` to `toolchain register` command`:
```
rye toolchain register --dbg /path/to/your/python/with/debug/symbols
```
Regards,
Charbel

### CODE REVIEW

**Comment by mitsuhiko** [comment]
Generally very much in favor. I think there will still be a bootstrapping issue for the most part as the toolchain is already installed as part of the bootstrapping step. Likely this needs to already be baked into the `install.sh` script and the installer step somehow.

I wonder if `--dbg` is needed or if we can't auto detect that. The `INSPECT_SCRIPT` already runs in the context of the Python installation, would it make sense to auto detect the debug flag in there?

**Comment by mitsuhiko** [comment]
#269 is autodetecting `Py_DEBUG` now which I think is nicer. For edge cases you can still manually name it which I think is clearer. I would take out that `--dbg` specific part here.

**Comment by charbeljc** [comment]
> Generally very much in favor. I think there will still be a bootstrapping issue for the most part as the toolchain is already installed as part of the bootstrapping step. Likely this needs to already be baked into the `install.sh` script and the installer step somehow.
> 
> I wonder if `--dbg` is needed or if we can't auto detect that. The `INSPECT_SCRIPT` already runs in the context of the Python installation, would it make sense to auto detect the debug flag in there?

Except that `rye toolchain register` is genuine rust, and does not trigger the bootsrapping process...
So, if you register your system python 3.10 before any other command, you are there :sunglasses:

**Comment by charbeljc** [comment]
Tested with Python 3.10.6 as `/usr/bin/python3` 

```bash
# test-rye-bootstap.sh
rm -rf ~/.rye
rm -rf ./hello_zscaler
export RYE_NO_AUTO_INSTALL=1
rye toolchain list
rye toolchain register /usr/bin/python3
rye toolchain list
rye init hello_zscaler
rye toolchain list
echo "3.10.6" > hello_zscaler/.python-version
sed -e 's/3.11/3.10/g' hello_zscaler/pyproject.toml >tmp
cp tmp hello_zscaler/pyproject.toml
(cd hello_zscaler && rye sync)
rye toolchain list


```

**Comment by mitsuhiko** [comment]
I like this, but I will make the installer smarter so that it's possible to pre-register a toolchain at installation time and to avoid the fetch. I also think rather than enforcing `3.10` or a version in particular, I want to support a version range (eg: 3.9 minimum, not avoid 3.11 etc.). But I will follow up with this separately.

**Pull request merged**
