### PR TITLE
Support version command for rye

### PR DESCRIPTION
**Pull request by ischaojie**
closes https://github.com/mitsuhiko/rye/issues/285

```
➜  o git:(main) ✗ rye version
0.1.0
➜  o git:(main) ✗ rye version 0.2.0
version set to 0.2.0

```

### CODE REVIEW

**Review by T-256 — APPROVED** [review]
would be nice to have support increase `patch`, `minor` and `major` directly.
currently when we don't know the current version, should get it first then change it via writing new version completely.

examples:
```shell
> rye version
0.21.2
> rye version patch
0.21.3 (patch from 0.21.2)
> rye version minor
0.22.0 (minor from 0.21.3)
> rye version major
1.0.0 (major from 0.22.0)
> rye version 0.21.2
successfully changed from 1.0.0
```

**Comment by mitsuhiko** [comment]
I think it would be less confusing if automatic bumping was `rye version --bump=major` or something like that.

**Comment by T-256** [comment]
> I think it would be less confusing if automatic bumping was `rye version --bump=major` or something like that.

Agree, final design can be:

```fish
> rye version --help
Creates a new python project

Usage: rye version [OPTIONS] [NEW]

Arguments:
  [NEW]  set new semver2 compatible version

Options:
      --bump <BUMP>      bump the version via patch, minor or major
      --dump <DUMP>      dump the version via patch, minor or major
      --pre <PRE>        append pre-releases to version
```

**Comment by ischaojie** [comment]
This PR is just for the basic `version` command, `bump` and other features may be the next PR.

**Pull request merged**
