### PR TITLE
Auto install completion script to shell with --install flag

### PR DESCRIPTION
**Pull request by ischaojie**
@cnpryer helped add a script generation for shell completion https://github.com/mitsuhiko/rye/pull/97, it would be nice to add the script to the shell config file automatically.

Currently, only bash, zsh and fish are supported.

### CODE REVIEW

**Comment by cnpryer** [comment]
IMO this should be opt in behind something like `--install`. Modifying the environment like this should be super explicit. Or at least that's the behavior I'd prefer.

How I use this is I add to my `.zshrc` the following:
```
eval "$(rye self completion -s zsh)"
```

**Comment by mitsuhiko** [comment]
Agreed, this should be optional.

**Comment by ischaojie** [comment]
I just added `--install` for completion, happy to review my naive code.

**Comment by mitsuhiko** [comment]
There is a bit of an overlap of this with #155. I will have a look at if there is a way to have a more generic installation solution that includes this.

**Pull request closed without merging**
